#!/bin/sh

echo "(1) Check that rss feed's last date isn't already in shortlog"
. ./do-check-rss-date || exit 1
echo "Last date: $pubdate"

# (2) Switch to 'dist', download & git-add hosts file
. ./do-download-hosts || exit 1

